services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: book-catalog-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/books.db
      - PYTHONPATH=/app
    volumes:
      # Persist database data
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - book-catalog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: book-catalog-frontend
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - book-catalog-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Named volumes for data persistence
volumes:
  backend_data:
    driver: local

# Custom network for service communication
networks:
  book-catalog-network:
    driver: bridge